FROM registry.access.redhat.com/ubi9/go-toolset:1.22.9
User 0
RUN yum install -y git jq wget tar python3.12 python3.12-pip python3.12-devel podman skopeo make gcc automake binutils && \
    yum clean all && rm -rf /var/cache/dnf/*
RUN ln -sf /usr/bin/python3.12 /usr/bin/python3 && \
    ln -sf /usr/bin/python3.12 /usr/bin/python
# Install uv - fast Python package installer for running registry REST API tests (pip installs to /usr/local/bin, works when run as non-root)
RUN python3 -m pip install --break-system-packages --no-cache-dir uv
# So python and uv are found when pipeline runs as non-root (PATH can be minimal)
ENV PATH="/usr/local/bin:/usr/bin:${PATH}"
RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && chmod +x oc && mv oc /usr/local/bin/
RUN ln -s /usr/local/bin/oc /usr/bin/kubectl
